AtomicFinance/bitcoin-abstraction-layer

packages/bitcoin-cfd-provider/lib/BitcoinCfdProvider.ts, packages/bitcoin-cfd-provider/lib/CfdInterfaces.d.ts, packages/bitcoin-cfd-provider/lib/cfdjsHelper.ts, packages/bitcoin-cfd-provider/package.json, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/bitcoin-dlc-provider/lib/DlcInterfaces.d.ts, packages/bitcoin-dlc-provider/lib/cfddlcjsHelper.ts, packages/bitcoin-dlc-provider/lib/models/DlcParty.ts, packages/bitcoin-dlc-provider/package.json, packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts, packages/client/lib/Cfd.ts, packages/client/lib/CfdInterfaces.d.ts, packages/client/lib/Dlc.ts, packages/client/lib/DlcInterfaces.d.ts, packages/client/package.json, webpack/webpack.config.js
`cfd-dlc-js` is compatible with node, `cfd-dlc-js-wasm` is compatible with web
`cfd-dlc-js-wasm` is compatible with react-native, however, it requires some workarounds.
This PR modifies CAL finance `BitcoinDlcProvider` and `BitcoinCfdProvider` to allow for `cfd-dlc-js` or `cfd-dlc-js-wasm` and `cfd-js` or `cfd-js-wasm` to be passed in rather than included natively in the library, to enable it to be used more easily in many environments.
=> Add compatibility for React Native

.gitignore, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/bitcoin-dlc-provider/lib/models/DlcParty.ts, packages/bitcoin-dlc-provider/lib/models/MutualClosingMessage.ts, packages/bitcoin-dlc-provider/lib/models/Output.ts, packages/client/lib/@types/@atomicfinance/bitcoin-dlc-provider/index.d.ts, packages/client/lib/Dlc.ts, tests/integration/common.ts, tests/integration/dlc/dlc.test.ts
A DLC is simply a 2-of-2 multisig with additional off-chain data for exiting with oracle signature or refund.
If participants wish to exit early, they can create a mutual close transaction.
This PR:
- Adds initiateEarlyExit and finalizeEarlyExit to BitcoinDlcProvider to allow parties to generate MutualClosingMessage offer and pass to counterparty, who then can sign and broadcast
- Adds multisig tests which tests the functionality of both initiateEarlyExit and finalizeEarlyExit
=> Add early exit functionality bitcoin-dlc-provider

packages/bitcoin-dlc-provider/lib/models/DlcParty.ts, packages/bitcoin-dlc-provider/lib/models/PartyInputs.ts
Since DLC adaptor version, sweep privkeys have been unnecessary since CETs spend directly to payoutSPK
=> Remove unnecessary sweep privkey

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/client/lib/Dlc.ts, tests/integration/common.ts, tests/integration/dlc/dlc.test.ts
This PR adds `isOfferer` fn to `BitcoinDlcProvider` for checking if the wallet is the offerer based on DlcOffer and DlcAccept messages (specifically checking the fund public key)
It also replaces `isLocalParty` with `isOfferer` bool
=> Replace isLocalParty with isOfferer

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/client/lib/Dlc.ts, tests/integration/utxos/utxos.test.ts
This PR adds `inputToFundingInput` and `fundingInputToInput` to DLC Client interface
=> Add inputToFundingInput to dlc client interface

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
This PR ensures `BitcoinDlcProvider` runs `findAddress` on both non-change and change addresses when getting derivationPath
=> Fix fundingInputToInput with findAddress for change

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts, packages/client/lib/Wallet.ts, packages/types/lib/financewallet.ts, tests/integration/wallet/wallet.test.ts
This PR implements `quickFindAddress` into `BitcoinWalletProvider`
This works by deriving the first 5 change and non-change addresses and checking if they match any of the addresses provided, continuing in a loop until an address is found. 
It is an improvement on `findAddress` which requires you to specify change or non-change address.
=> Implement quickFindAddress into BitcoinWalletProvider

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/dlc.test.ts
This PR adds event validation for execute in `BitcoinDlcProvider`
This ensures that a transaction is not executed with an incorrect attestation
=> Add event validation for execute in BitcoinDlcProvider

packages/bitcoin-dlc-provider/package.json
This PR removes unnecessary is-node module from DlcProvider
=> Remove is-node dlc provider

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/dlc.test.ts
This PR ensures `cetLocktime` is passed to `CfdDlc` in `BitcoinDlcProvider`
Previously, locktime's were always set to 0. This fixes that problem.
=> Ensure cet locktime passed to cfd dlc in BitcoinDlcProvider

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/dlc.test.ts
* Fix modifying the actual intervals array in the contract descriptor (.sort modifies array in-place)
* Fix rounding interval lookup (should be looking up based on outcome, not on payout)
=> Fix outcome index finding

package.json, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/types/lib/dlc.ts, tests/integration/dlc/dlc.test.ts
This PR updates CAL Finance to cfd-dlc-js v0.0.25 with to enable serial ids input and output ordering
=> Update for Serial Id Input and Output ordering

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/client/lib/Dlc.ts, packages/types/lib/dlc.ts, tests/integration/dlc/dlc.test.ts, tests/integration/utils/WrappedCfdDlcJs.ts
This PR adds `createBatchDlcClose` which generates multiple DlcClose messages using `initiatorPayouts` array. 
It also fixes ordering of outputs to use `payoutSerialId` to determine ordering of outputs for `createDlcClose` and `finalizeDlcClose`
Note: This PR does not add support for multiple funding inputs for `createBatchDlcClose`. This has been added as a `TODO` to be added at a later date.
=> Add DlcClose multiple using CFD CalculateEcSignatures

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/client/lib/Dlc.ts, packages/types/lib/dlc.ts, tests/integration/dlc/dlc.test.ts
This PR adds `verifyBatchDlcClose` which allows verification of multiple DlcClose message closing signatures
Note: It does not support multiple funding inputs on these DlcClose messages (and throws and Error if any DlcClose provided contains fundingInputs)
=> Add verifyBatchDlcClose

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/client/lib/Dlc.ts, packages/types/lib/dlc.ts, tests/integration/dlc/dlc.test.ts
This PR exposes `createDlcTxs` fn which allows `dlcTxs` object to be recreated using only `DlcOffer` and `DlcAccept`
=> Expose createDlcTxs fn

README.md, packages/provider/lib/Provider.ts, packages/types/lib/models/Input.ts, tests/integration/common.ts, tests/integration/dlc/dlc.test.ts
Rename `chainabstractionlayer` to `chainify`
[liquality/chainabstractionlayer](https://github.com/liquality/chainabstractionlayer) was recently renamed to [liquality/chainify](https://github.com/liquality/chainify)
Since this library builds on top of [liquality/chainabstractionlayer](https://github.com/liquality/chainabstractionlayer), it made sense to rename this library to chainify-finance
=> 📝docs: rename chainabstractionlayer to chainify

.changeset/khaki-humans-push.md, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/custom-oracle.test.ts, yarn.lock
This PR fixes clamp for BigNumber payouts in `FindOutcomeIndexFromPolynomialPayoutCurvePiece`
Specifically the clamp should’ve been taking the max and min payouts for the `PolynomialPayoutCurvePiece` but was previously defaulting to `0` or `totalCollateral`
Added a test where this bug was originally found, and ensures we no longer run into the following error
`Failed to Find OutcomeIndex From PolynomialPayoutCurvePiece. Payout Group found but incorrect group index`
=> Fix clamp for BigNumber in FindOutcomeIndexFromPolynomialPayoutCurvePiece

packages/bitcoin-js-wallet-provider/package.json, packages/bitcoin-node-wallet-provider/package.json, packages/bitcoin-utils/package.json, packages/utils/package.json, tests/integration/dlc/custom-oracle.test.ts, tests/integration/utils/WrappedCfdDlcJs.ts, yarn.lock
Fix unit in custom oracle tests
There are two tests affected
`Custom Strategy Oracle POC numdigits=18` and `Custom Strategy Oracle POC numdigits=21`
numdigits = 18 original:
```ts
const { payoutFunction } = LinearPayout.buildPayoutFunction(
80000000n,
120000000n,
80000n,
120000n,
oracleBase,
numDigits,
);
...
const unit = 'Bits';
```
Representing `minPayout = 80000000n, maxPayout = 120000000n, startOutcome = 80000n, endOutcome = 120000n`
`minPayout` is in sats, so that's 0.8 BTC (`80,000,000 / 1e8`)
According to https://en.bitcoin.it/wiki/Units `micro-bitcoin` or `bit` is `0.000001`
`0.000001 * 1e6 = 1 bit`
Therefore
`0.8 * 1e6 = 800,000 bits` 
However in the example, `startOutcome` is `80,000 bits` which is incorrect
On the other hand 👇 
numdigits = 21 original:
```ts
const { …
```
=> ✅test: fix unit for bits in custom oracle test

package.json, packages/bitcoin-js-wallet-provider/lib/BitcoinJsWalletProvider.ts, packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts, tests/integration/common.ts, tests/integration/wallet/wallet.test.ts, yarn.lock
Add custom starting `addressIndex` for js wallet provider
This allows `getUsedAddress` and `getUnusedAddress` to start searching for addresses at a certain `addressIndex`
After a wallet becomes significantly used, to speed up queries, the `startingIndex` should be incremented to whatever index is deemed safe.
=> ✨ feat: custom starting address index js wallet

.changeset/good-lies-float.md, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/dlc.test.ts, tests/integration/utils/contract.ts, yarn.lock
Fix find outcome index hyperbola edge case
In certain cases, the `roundedPayout` in `FindOutcomeIndexFromHyperbolaPayoutCurvePiece` does not equal the larger payout value in the payoutGroups
In this case, when searching for the appropriate group index, you shoudl check if the `payoutGroup.payout` equals the `roundedPayout` and also check if it equals the `payout` from `clampBN(hyperbolaCurve.getPayout(outcome));` and update the returned `index` accordingly
This will ensure the right `index` and right CET signature is found when executing the DLC
=> 🐛 fix: find outcome index hyperbola edge case

.changeset/tiny-pumpkins-trade.md, packages/bitcoin-rpc-provider/package.json
Fix the types issues with bitcoin-rpc-provider
It was looking for types in the wrong directory. Removes the incorrect line associated with this
=> fix: types with bitcoin-rpc-provider

.changeset/gold-ducks-clean.md, package.json, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/common.ts, tests/integration/config.ts, tests/integration/dlc/custom-oracle.test.ts, tests/integration/dlc/dlc.test.ts, tests/integration/models/Oracle.ts, tests/integration/utils/contract.ts
Add enum support to `BitcoinDlcProvider` 
Specifically, it adds support for the creation of simple binary options (trump won or kamala won) into the existing `createDlcOffer`, `acceptDlcOffer`, `signDlcAccept`, `finalizeDlcSign`, and `execute` functions in `BitcoinDlcProvider`
=> feat: add enum support to dlc provider

.changeset/grumpy-toes-accept.md, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, tests/integration/dlc/dlc.test.ts, tests/integration/utils/contract.ts
Fix enum hashed outcomes
Outcome needs to be 32 bytes, according to `ContractDescriptorV0`
https://github.com/AtomicFinance/node-dlc/blob/master/packages/messaging/lib/messages/ContractDescriptor.ts#L64
Therefore, outcome needs to be hashed, when checking oracleAnnouncement vs attestation and when signing with the oracle
=> fix: enum hashed outcomes

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts, packages/types/lib/models/Amount.ts, packages/types/lib/models/Input.ts, packages/types/lib/models/Utxo.ts, yarn.lock
When installing this package in projects with strict TypeScript configuration, compilation fails with several type errors:
1. `Amount.fromJSON()` returns `undefined` when json is falsy, but return type expects `Amount`
2. `Input.toUtxo()` uses `amount` variable before assignment in some code paths  
3. Type mismatch between `Input.derivationPath` (optional) and `Utxo.derivationPath` (required)
- **Amount.ts**: Fix `fromJSON()` method to return `Amount.FromSatoshis(0)` instead of `undefined` when input is falsy
- **Input.ts**: Add fallback case to ensure `amount` variable is always assigned before use
- **Utxo.ts**: Make `derivationPath` parameter optional and reorder constructor parameters to follow TypeScript conventions (optional parameters last)
- **BitcoinDlcProvider.ts**: Update `new …
=> fix: TypeScript strict mode compilation errors in type models

.changeset/empty-news-share.md, packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
The `BitcoinDlcProvider` was importing `DlcInputInfo` and `InputSupplementationMode` from a specific internal model file path (`@atomicfinance/types/lib/models/Input`) instead of using the main package export.
- Move `DlcInputInfo` and `InputSupplementationMode` to the main `@atomicfinance/types` import block
- Remove the separate import from the internal model file path
- Maintain alphabetical ordering in the import list
- **Consistent import style**: All types now imported from the main package export
- **Better encapsulation**: Uses public API instead of reaching into internal file structure
- **Improved maintainability**: Changes to internal file structure won't break imports
- **Cleaner code**: Consolidated imports in a single location
This is a non-breaking refactor that improves …
=> refactor: Organize imports in BitcoinDlcProvider

.changeset/tasty-sides-enjoy.md, packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts, tests/integration/dlc/dlc.test.ts
Implements proper contract ID computation that matches the rust-dlc/ddk implementation, replacing the previous simple XOR approach
- **Added `computeContractId` method** that properly computes contract IDs according to the DLC specification
- **Includes fund output index** in the calculation (was previously missing)
- **Implements byte order reversal** for the fund transaction ID as required by the spec
- **Replaces simple XOR operations** with the proper contract ID computation in both DLC accept and sign flows
- **Adds comprehensive test case** using the same test vectors as the Rust implementation
- **Removes unused import** of `xor` function
The new implementation follows the exact same logic as rust-dlc's `compute_id` function:
1. XORs fund transaction ID (with byte order reversal) …
=> feat: implement rust-dlc compatible contract ID computation

.changeset/dirty-zoos-flash.md, packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts, tests/integration/common.ts, tests/integration/dlc/dlc.test.ts
Ensure consistent sequence numbers in funding signature verification
Also add `getFundingTransactionSighash` and `getFundingTransactionSighashDetails` to be able to verify sighash
=> fix: ensure consistent sequence numbers in funding signature verification

.changeset/salty-cities-brush.md, packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts, packages/bitcoin-ddk-provider/lib/utils/Utils.ts, tests/integration/dlc/dlc.test.ts
- **`sortFundingInputsBySerialId()`** - centralized function for sorting funding inputs by serial ID
- handles the common pattern of `Number(a.inputSerialId) - Number(b.inputSerialId)`
- ensures consistent sorting behavior across all DLC operations
- replace 6+ instances of manual funding input sorting with utility function calls
- simplify `FindOutcomeIndexFromHyperbolaPayoutCurvePiece` by removing unnecessary parameter wrapping
- remove redundant type casting in funding input processing
- clean up array creation and sorting boilerplate
- remove debug `console.log` statements from tests
- improve readability by reducing nested operations
- **reduced duplication**: eliminates repeated sorting logic
- **better maintainability**: changes to sorting behavior only need to be made in one place …
=> refactor: extract funding input sorting utility & cleanup
