packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts
packages/client/lib/Client.ts
packages/client/lib/Wallet.ts
tests/integration/common.ts
tests/integration/wallet/wallet.test.ts

Add unusedAddress to `BitcoinWalletProvider` which contains blacklist to avoid address reuse
Add tests for getUnusedAddress

Unused address blacklist

---

lerna.json
packages/bitcoin-cfd-provider/package.json
packages/bitcoin-dlc-provider/package.json
packages/bitcoin-wallet-provider/package.json
packages/bundle/package.json
packages/client/package.json
packages/provider/package.json

Bump to 1.0.0

---

packages/bitcoin-networks/lib/@types/@liquality/types/index.ts
packages/bitcoin-networks/lib/@types/@liquality/types/network.ts
packages/bitcoin-networks/lib/index.ts
packages/bitcoin-networks/package.json
packages/bitcoin-networks/tsconfig.json

Add bitcoin networks module

---

tests/integration/common.ts
tests/integration/config.ts
tests/integration/utils/WrappedCfdDlcJs.ts
tests/integration/utils/cfdDlcJsWorker.js

Add `getWrappedCfdDlcJs` for parallelizing methods `CreateCetAdaptorSignatures` and `VerifyCetAdaptorSignatures`
Update common.ts for loading parallelized `cfdDlcJs`

Parallelize cfd dlc js

---

packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts
packages/bitcoin-wallet-provider/package.json

Add TS bitcoin-networks to BitcoinWalletProvider

Add TS bitcoin-networks to BitcoinWalletProvider and lint

---

tests/integration/utxos/utxos.test.ts

Add tests for getUtxosForAmount and inputToFundingInput

Add utxos tests

---

LICENSE
LICENSE.md
lerna.json
package.json
packages/bitcoin-cfd-provider/package.json
packages/bitcoin-dlc-provider/package.json
packages/bitcoin-networks/package.json
packages/bitcoin-wallet-provider/package.json
packages/bundle/package.json
packages/client/package.json
packages/provider/package.json

Bump to 2.0.0-alpha.0
- Set @node-dlc verison to 2.0.0-alpha.0
- Update module authors to info@atomic.finance
- Update module descriptions
- Switch to GPL3 License

2.0.0-alpha.0

---

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
tests/integration/dlc/dlc.test.ts

This PR ensures that DlcOffer and DlcAccept fundingpubkey can't be equal

Add fundingpubkey duplicate check

---

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
tests/integration/dlc/dlc.test.ts

This PR fixes rounded payout calculation by ensuring all min and max values are clamped.

Fix rounded payout calculation

---

tests/integration/utils/WrappedCfdDlcJs.ts
tests/integration/utils/cfdDlcJsWorker.js

This PR fixes the Cfd Dlc Js wrapper for tests (previously causing malloc issues).

Fix Cfd Wrapper for tests

---

packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts

Should be an object instead of array

Fix unusedAddressesBlacklist

---

packages/bitcoin-cfd-provider/lib/BitcoinCfdProvider.ts
packages/bitcoin-cfd-provider/package.json

This PR removes unnecessary is-node from CfdProvider

Remove is-node from cfd provider

---

packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts

This PR fixes address reuse on seed rehydration

Fix address reuse on seed rehydration

---

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts

Added remaining validations from the [specs](https://github.com/discreetlogcontracts/dlcspecs/blob/master/Protocol.md#the-accept_dlc-message)

Add DLC Validations

---

packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts

ensure funding inputs are enough to cover collateral + fees

Add DLC validations for fundingInputs and collaterals

---

package.json
packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
tests/integration/dlc/dlc.test.ts
tests/integration/utils/contract.ts

Support Disjoint Union DLCs

---

package.json
packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
packages/types/lib/dlc.ts
tests/integration/dlc/dlc.test.ts

This PR updates CAL Finance to cfd-dlc-js v0.0.25 with to enable serial ids input and output ordering

Serial id update

---

README.md

This PR updates README with DlcSpec compliance

Update README with DlcSpec compliance

---

package.json
yarn.lock

This PR bumps lerna to `4.0.0`

Bump lerna

---

.changeset/short-forks-jam.md
packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts
yarn.lock

Increase address gap from 20 to 30
Temporary stop-gap solution until custom gap address limit is implemented

🔧 config: increase address gap from 20 to 30

---

.changeset/large-sloths-chew.md

Custom starting address index changeset

🔧 config: custom starting address index changeset

---

.changeset/forty-rivers-serve.md
packages/bitcoin-js-wallet-provider/lib/BitcoinJsWalletProvider.ts
packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts
tests/integration/common.ts
tests/integration/wallet/wallet.test.ts

Set up custom starting change address

Custom starting change address index

---

.changeset/swift-kiwis-smash.md
packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts

Fix rounding error find payout

🐛 fix: rounding error find payout

---

docs/00-overview.md
docs/01-introduction.md
docs/02-getting-started.md
docs/03-integration-guide.md
yarn.lock

Add intro, getting started and integration docs

📝 docs: intro, getting strated and integration

---

justfile

Add justfile for easier dev cmd standardization

build: add justfile

---

.changeset/thin-snakes-jump.md
packages/bitcoin-dlc-provider/lib/BitcoinDlcProvider.ts
packages/bitcoin-dlc-provider/package.json
packages/bitcoin-js-wallet-provider/lib/BitcoinJsWalletProvider.ts
packages/bitcoin-js-wallet-provider/package.json
packages/bitcoin-node-wallet-provider/lib/BitcoinNodeWalletProvider.ts
packages/bitcoin-node-wallet-provider/package.json
packages/bitcoin-utils/lib/bitcoinjs-lib-classify.d.ts
packages/bitcoin-utils/lib/index.ts
packages/bitcoin-utils/package.json
packages/bitcoin-wallet-provider/lib/BitcoinWalletProvider.ts
packages/bitcoin-wallet-provider/package.json
packages/utils/lib/bitcoin.ts
packages/utils/package.json
tests/integration/dlc/custom-oracle.test.ts
tests/integration/dlc/dlc.test.ts
tests/integration/wallet/wallet.test.ts
yarn.lock

Upgrade bitcoinjs-lib v6 with ECPair migration

feat: upgrade bitcoinjs-lib v6 with ECPair migration

---

.changeset/lucky-nights-laugh.md
packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts

This PR ensures that signatures passed for refund are DER signatures

fix: ensure der signature logic

---

.changeset/fast-steaks-give.md
packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts

Ensure refund tx includes sequence from original refund tx in BitcoinDdkProvider
Also add a check to make sure txid matches original refund tx created by ddk

fix: refund tx sequence ddk provider

---

.changeset/sweet-schools-tell.md
packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts

Switch funding signature to use DER encoding for BitcoinDdkProvider (for ddk compatibility)

fix: fund tx compact to der witness funding sig

---

.changeset/eighty-pillows-bow.md
packages/bitcoin-ddk-provider/lib/BitcoinDdkProvider.ts
packages/client/lib/Dlc.ts
tests/integration/dlc/dlc.test.ts

Fix fundingInputToInput with derivationPath dlcInput

fix: fundingInputToInput w/ derivationPath dlcInput
